#!/usr/bin/env bash
# this script installing nginx with specific requirements

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
