#!/usr/bin/env bash
# this script config nginx to redirect to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/shorts/ioJ-H2q38HI permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
