#!/usr/bin/env bash
# this script configuring web server

sudo apt-get -y update
sudo apt-get -y install nginx

HTML_PATH="/var/www/html"
ERROR_404_PATH="/usr/share/nginx/html/error_404.html"

echo "Hello World!" | sudo tee "$HTML_PATH/index.html"
echo "Ceci n'est pas une page" | sudo tee "$ERROR_404_PATH"

NGINX_CONF_PATH="/etc/nginx/sites-available/default"

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root $HTML_PATH;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        rewrite ^/redirect_me https://www.youtube.com/shorts/ioJ-H2q38HI permanent;
    }

    add_header X-Served-By $HOSTNAME;

    error_page 404 /error_404.html;
    location = /error_404.html {
        root /usr/share/nginx/html;
        internal;
    }
}" > $NGINX_CONF_PATH

sudo service nginx restart
