#!/usr/bin/env bash
# This script displays text according to some singals

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid; exit 0' SIGQUIT
done
